version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000 
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: Qazwsx123_
      MYSQL_ROOT_PASSWORD: Qazwsx123_
    volumes:
      - .dbdata:/var/lib/mysql
